services:
  # 1) PgBouncer (service privé)
  - type: pserv
    name: pgbouncer-deepl-trad
    runtime: docker
    repo: https://github.com/render-oss/docker-pgbouncer
    region: frankfurt
    envVars:
      # récupère l'Internal URL de TA DB existante par son nom de service Render
      - key: DATABASE_URL
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: connectionStringInternal
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: "500"
      - key: DEFAULT_POOL_SIZE
        value: "50"

  # 2) Ton Web Service Node
  - type: web
    name: trad-api
    env: node
    region: frankfurt
    buildCommand: "npm ci"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      # Fallback: URL interne directe de TA DB existante
      - key: DATABASE_URL
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: connectionStringInternal
      - key: PROJECT_ID
        value: "A REMPLACER PAR TON UUID PROJET"
      - key: NODE_ENV
        value: production
