services:
  # 1) PgBouncer (service privé)
  - type: pserv
    name: pgbouncer-deepl-trad
    runtime: docker
    repo: https://github.com/render-oss/docker-pgbouncer
    region: frankfurt
    envVars:
      # URL complète (externe) fournie par Render
      - key: DATABASE_URL
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: "500"
      - key: DEFAULT_POOL_SIZE
        value: "50"

  # 2) Ton Web Service Node
  - type: web
    name: trad-api
    env: node
    region: frankfurt
    buildCommand: "npm ci"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      # Récupère les 'morceaux' de la connexion interne
      - key: DB_HOST
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: host
      - key: DB_PORT
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: port
      - key: DB_NAME
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: database
      - key: DB_USER
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: "Traduction Français vers autres langues"
          property: password
      # Tu pourras ajouter POOL_DATABASE_URL après déploiement (avec le host interne de PgBouncer)
      - key: PROJECT_ID
        value: "a7b6daa8-7374-43e2-84f2-477fa999697e"
      - key: NODE_ENV
        value: production
